---
- name: First Pull Demo Ansible Playbook
  hosts: localhost
  tasks:
      - name: print hello world
        debug:
            msg:"hell world!!.."
        - name: print host name
          debug:
              var: ansible_host
        - name: print Ubantu version
          debug:
              var: ansible_distribution
